// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6BvPjKHHX58YhMCDtojDLNPQc4WMoq_c',
    appId: '1:890066810144:web:e39522de41cb09296d5345',
    messagingSenderId: '890066810144',
    projectId: 'my-dorm-f2cad',
    authDomain: 'my-dorm-f2cad.firebaseapp.com',
    storageBucket: 'my-dorm-f2cad.firebasestorage.app',
    measurementId: 'G-SP4Q3HYX96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA40fGIO18DU2WfV-rkJ6kC20WcoaD8mQk',
    appId: '1:890066810144:android:34ac35e42ed9dae56d5345',
    messagingSenderId: '890066810144',
    projectId: 'my-dorm-f2cad',
    storageBucket: 'my-dorm-f2cad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkIxEgSReDyFVl3cOfENxhJ049BqfkiOU',
    appId: '1:890066810144:ios:e9d16c6b9996d7da6d5345',
    messagingSenderId: '890066810144',
    projectId: 'my-dorm-f2cad',
    storageBucket: 'my-dorm-f2cad.firebasestorage.app',
    iosBundleId: 'com.example.myDorm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkIxEgSReDyFVl3cOfENxhJ049BqfkiOU',
    appId: '1:890066810144:ios:e9d16c6b9996d7da6d5345',
    messagingSenderId: '890066810144',
    projectId: 'my-dorm-f2cad',
    storageBucket: 'my-dorm-f2cad.firebasestorage.app',
    iosBundleId: 'com.example.myDorm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6BvPjKHHX58YhMCDtojDLNPQc4WMoq_c',
    appId: '1:890066810144:web:aab07d42a9fa42016d5345',
    messagingSenderId: '890066810144',
    projectId: 'my-dorm-f2cad',
    authDomain: 'my-dorm-f2cad.firebaseapp.com',
    storageBucket: 'my-dorm-f2cad.firebasestorage.app',
    measurementId: 'G-1ZQPZ28K0G',
  );
}
